1.IMPORT LIBRARIES

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.ensemble import RandomForestRegressor

2.LOAD DATASET

In [2]:
df = pd.read_csv("KIET_Women_Safety_365_Days_2023_2026 (1).csv")

3.UNDERSTAND THE DATASET

In [3]:
df.head()

,Year,Day_of_Year,Date,Place,Time_Period,Lighting_Score,CCTV_Available,Crowd_Density,Security_Nearby,Synthetic_Incident_Index,Risk_Score,Data_Status
0,2023,1,2023-01-01,KIET College Bus Stop,Morning,3,0,5,0,3.24,64,Synthetic/assumption data
1,2023,1,2023-01-01,KIET College Bus Stop,Afternoon,3,1,3,0,4.09,70,Synthetic/assumption data
2,2023,1,2023-01-01,KIET College Bus Stop,Evening,3,0,5,0,3.20,64,Synthetic/assumption data
3,2023,1,2023-01-01,KIET College Bus Stop,Night,1,0,1,0,5.00,100,Synthetic/assumption data
4,2023,1,2023-01-01,College Main Gate,Morning,3,1,5,1,1.01,31,Synthetic/assumption data

In [4]:
df.shape

(75920, 12)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 75920 entries, 0 to 75919
Data columns (total 12 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Year                      75920 non-null  int64
 1   Day_of_Year               75920 non-null  int64
 2   Date                      75920 non-null  object
 3   Place                     75920 non-null  object
 4   Time_Period               75920 non-null  object
 5   Lighting_Score            75920 non-null  int64
 6   CCTV_Available            75920 non-null  int64
 7   Crowd_Density             75920 non-null  int64
 8   Security_Nearby           75920 non-null  int64
 9   Synthetic_Incident_Index  75920 non-null  float64
 10  Risk_Score                75920 non-null  int64
 11  Data_Status               75920 non-null  object
dtypes: float64(1), int64(7), object(4)
memory usage: 7.0+ MB

In [6]:
df.describe()

,Year,Day_of_Year,Lighting_Score,CCTV_Available,Crowd_Density,Security_Nearby,Synthetic_Incident_Index,Risk_Score
count,75920.000000,75920.000000,75920.000000,75920.000000,75920.000000,75920.000000,75920.000000,75920.000000
mean,2024.500000,183.000000,3.426818,0.675803,3.623354,0.587842,2.137230,47.358851
std,1.118041,105.366723,0.947518,0.468077,1.595871,0.492226,1.625838,25.548877
min,2023.000000,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,15.000000
25%,2023.750000,92.000000,3.000000,0.000000,2.000000,0.000000,0.810000,29.000000
50%,2024.500000,183.000000,4.000000,1.000000,4.000000,1.000000,1.820000,42.000000
75%,2025.250000,274.000000,4.000000,1.000000,5.000000,1.000000,3.230000,63.000000
max,2026.000000,365.000000,5.000000,1.000000,5.000000,1.000000,5.000000,100.000000

4.CHECKING NULL VALUES

In [7]:
df.isnull().sum()

Year                        0
Day_of_Year                 0
Date                        0
Place                       0
Time_Period                 0
Lighting_Score              0
CCTV_Available              0
Crowd_Density               0
Security_Nearby             0
Synthetic_Incident_Index    0
Risk_Score                  0
Data_Status                 0
dtype: int64

In [8]:
df["Lighting_Score"] = df["Lighting_Score"].fillna(
    df["Lighting_Score"].median()
)

5.CHECK AND REMOVE DUPLICATE ROWS, COLUMNS

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
df = df.drop_duplicates()

6.CONVERTING DATE COLUMN

In [11]:
df["Date"] = pd.to_datetime(df["Date"])

7.CHECK CATEGORICAL COLUMNS

In [12]:
df["Place"].unique()

array(['KIET College Bus Stop', 'College Main Gate',
       'College Admission Office', 'College Transport Bus Area',
       'Girls Hostel', 'Boys Hostel', 'College Ground',
       'College Back Gate', 'College A Block', 'College B Block',
       'College Canteen', 'Girls Canteen', 'College Steps'], dtype=object)

In [13]:
df["Time_Period"].unique()

array(['Morning', 'Afternoon', 'Evening', 'Night'], dtype=object)

8.ENCODE CATEGORICAL DATA

In [14]:
df = pd.get_dummies(
    df,
    columns=["Place", "Time_Period"],
    drop_first=True
)

9.SELECT INPUT FEATURES

In [15]:
X = df[
    [
        "Lighting_Score",
        "CCTV_Available",
        "Crowd_Density",
        "Security_Nearby",
        "Synthetic_Incident_Index"
    ]
]

10.SELECT TARGET

In [16]:
y = df["Risk_Score"]

11. TRAIN-SPLIT THE DATA

In [17]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

In [18]:
X_train.shape

(60736, 5)

In [19]:
X_test.shape

(15184, 5)

In [20]:
y_train.shape

(60736,)

In [21]:
y_test.shape

(15184,)

12. FEATURE SCALING

In [22]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [23]:
X_train_scaled[:5]

array([[-2.5516991 , -1.44360139, -1.64042546, -1.1953481 ,  1.7545919 ],
       [-2.5516991 ,  0.692712  , -1.64042546,  0.83657639,  1.7545919 ],
       [-1.49906755,  0.692712  , -1.64042546,  0.83657639,  1.5215003 ],
       [ 0.60619557, -1.44360139,  0.86354239, -1.1953481 , -0.41070644],
       [ 1.65882712,  0.692712  ,  0.86354239, -1.1953481 , -1.28173297]])

13.CREATE POLYNOMIAL FEATURE

In [24]:
from sklearn.preprocessing import PolynomialFeatures
poly = PolynomialFeatures(degree=2)
X_train_poly = poly.fit_transform(X_train_scaled)
X_test_poly = poly.transform(X_test_scaled)